name: My Python CI with SonarQube

on: [push]

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 10

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        cd src
        python -m pytest

    - name: Run SonarScanner
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: |
        sonar-scanner \
          -Dsonar.login=$SONAR_TOKEN \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.projectKey=my_project_key \
          -Dsonar.sources=. \ 
